#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import awsm
from datetime import datetime
import sys


def run():
    start = datetime.now()

    configFile = '/code/awsm/test_data/RME_run/config_pysnobal.ini'
    if len(sys.argv) > 1:
        configFile = sys.argv[1]

    # =========================================================================
    # Initialize and run basin
    # =========================================================================
    #

    # 1. initialize
    # try:
    with awsm.framework.framework.AWSM(configFile) as a:

        a.runawsm()
        
        a._logger.info('AWSM finished in: {}'.format(datetime.now() - start))


if __name__ == '__main__':
    run()
